name: sync server root with server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: cd www && git pull
